### ISSUE TITLE
Add category artifical inteligence

### ISSUE THREAD

**Issue by luisa-maria1111** [marmelo/tech-companies-in-portugal#232]
Not sure if it is relevant, but maybe it could be useful to add this category. And as an example, the company Smartex!

**Comment by afonsojramos** [comment]
I think this makes sense as there has been a great number of companies within this area of expertise opening up offices in Portugal!

**Comment by marmelo** [comment]
I have mixed feelings, because most of AI companies are not pure AI.
I mean, they apply AI in a specific vertical. And those verticals are the categories we now have.

For instance, the mentioned Smartex.ai company (after a quick look at their site) is focused on the textile manufacturing process.
So it would fit in the [Industry](https://github.com/marmelo/tech-companies-in-portugal#industry-factory) category.

@luisa-maria1111 feel free to create a Pull Request for Smartex!

Thanks.

**Comment by pedrorijo91** [comment]
agree with @marmelo . Feedzai and Onfido use AI, but for fintech. For most of them AI is a tool almost at the same level than saying they use Java, Python, JS, or whatever

**Comment by afonsojramos** [comment]
I see your point in relation to Smartex in specific, however, I feel like there are some companies that align first with AI. Furthermore, in terms of tech, Smartex actually aligns better with AI than the industry category. The AI skillset is very different from the others.

**Comment by marmelo** [comment]
I'm closing this issue.
Please reopen if still relevant.

**Comment by luisa-maria1111** [comment]
Agree with everything, that’s why I believe it should be possible to have a company in multiple categories. 

It’s important for someone looking for a company that focuses or at least has some verticals on AI to be able to quickly find here a list of related companies.
