### ISSUE TITLE
Add Glassdoor link to each company

### ISSUE THREAD

**Issue by filfreire** [marmelo/tech-companies-in-portugal#27]
👋  @marmelo, similar to was done for https://github.com/filfreire/theOPOmarket, we could add the Glassdoor link of the company next to the careers page.

**Comment by marmelo** [comment]
I wanted to refrain from adding more info to reduce the horizontal space.  
But I agree that Glassdoor is a very important addition.

Let me check if I can manage to fit the extra links without compromise readability.

Thanks!

**Comment by ptalmeida** [comment]
@marmelo Maybe add it under the emogi ⭐?

**Comment by orium** [comment]
I would suggest :mag_right:

**Comment by oandreeeee** [comment]
> I would suggest 🔎

Or a 🚪 

😸

**Comment by marmelo** [comment]
Hi @ptalmeida, I like your suggestion but I do prefer the 🔎 @orium suggested.

**Comment by marmelo** [comment]
I have created a POC in the following branch:
https://github.com/marmelo/tech-companies-in-portugal/tree/add-glassdoor-links

Only two companies have the new link yet.
What do you think?

**Comment by leplastic** [comment]
We also have a "portuguese version" of GlassDoor: https://pt.teamlyzer.com/

I think one advantage of Teamalyzer over GlassDoor is some smaller portuguese companies can be present on Teamlyzer and not in GlassDoor (because it's a portuguese project). My idea would be including the GlassDoor link by default, and only if not available, include the Teamalyzer link (or viceversa), so we still remaing with a single icon. What do you think about this?

**Comment by shizpi** [comment]
I agree with adding Teamlyzer. I would actually add it over Glassdoor.

Glassdoor has several known issues with deleting reviews when a company asks for it: https://www.sitejabber.com/reviews/glassdoor.com

**Comment by orium** [comment]
I would have both.  Glassdoor is the reference that everyone uses worldwide, so I think it should be there.

**Comment by vpereira01** [comment]
Solved by #209

**Comment by waldyrious** [comment]
> Solved by #209

@vpereira01 hmm, that doesn't add a linked icon to each entry, as was suggested in this issue. I would expect the actual resolution to be along the same lines of #210. WDYT?

**Comment by afonsojramos** [comment]
@waldyrious I would say that the search boxes on those services work pretty well. Otherwise, we would have to decide on Glassdoor vs Teamlyzer on a per-company basis, as their existence is not consistent across both. 
By just pointing in the right direction I would say that it already helps quite a lot.

**Comment by waldyrious** [comment]
Gotcha — actually I was just writing this comment (you were faster!) to mention that I have now seen the discussion that took place in #161, especially from [this comment](https://github.com/marmelo/tech-companies-in-portugal/pull/161#issuecomment-584397983) onward, which properly explains this decision and justifies closing this issue. Thanks for the quick response!
