### ISSUE TITLE
Rename Present Technologies.

### ISSUE THREAD

**Issue by marmelo** [marmelo/tech-companies-in-portugal#95]
Hi @samaxes, I am having some trouble with the length of Present Technologies.
Which change do you prefer?

1. Rename to **Present Tech**;
2. Rename to **Present**;
3. Add a line break between Present and Technologies.

Sorry and thanks!

**Comment by samaxes** [comment]
Hi @marmelo,
Changing the name of the company is not an option, but option 3 is acceptable.
However, wouldn't preventing the text from wrapping on the company column be a better and more robust solution? Especially since you have companies with even bigger names in other tables that can cause the same issue in the future.
